com:
  name: 嘻嘻嘻
spring:
  freemarker:
    # 设置模板后缀名
    suffix: .ftl
    # 设置文档类型
    content-type: text/html
    # 设置页面编码格式
    charset: UTF-8
    # 设置页面缓存
    cache: false
    # 设置ftl文件路径(需要配置)
    template-loader-path: classpath:/template
    #定义RequestContext的名称（项目根目录名称）
    request-context-attribute: request
  # 设置静态文件路径，js,css等
  mvc:
    static-path-pattern: /static/**
  data:
    mongodb:
      uri: mongodb://localhost:27017/springone
  datasource:
    #驱动信息配置
    url: jdbc:mysql://localhost:3306/springboottest?useUnicode=true&characterEncoding=utf-8
    driverClassName: com.mysql.jdbc.Driver
    username: root
    password: ljj125896
    #连接池信息配置
    type: com.alibaba.druid.pool.DruidDataSource
    #连接池初始数量
    initialSize: 5
    #最小数量
    minIdle: 5
    #最大数量
    maxActive: 30
    #最大等待时间（ms）
    maxWait: 60000
    #多长时间检测一次池里面的空闲连接，并关闭连接(关闭的前提是空闲时间大于timeBetweenEvictionRunsMillis的值-默认为30分钟)
    timeBetweenEvictionRunsMillis: 60000
    #申请连接时需要检测连接的空闲时间，如果大于上面属性配置的时间，则需要使用validationQuery对应sql判断连接是否有效
    testWhileIdle: true
    #用于检测连接是否有效的sql（配置的是mysql用的）
    validationQuery: select 1
    #空闲连接不被关闭的最长时间(ms)
    minEvictableIdleTimeMillis: 2000000
    #拦截器，其中wall用于防止sql注入
    filters: stat,wall,log4j
    #在池中取出连接时是否检查连接是否失效
    testOnBorrow: true
    #把连接放回池中时是否检测可用
    testOnReturn: false



mybatis:
  configuration:
    #对查询出来的字段自动进行驼峰转换
    map-underscore-to-camel-case: true
